equinor/hearing-test

- screens/TestScreen.js
- services/api/api-methods.js
- services/api/mocked-api-methods/index.js
- services/api/mocked-api-methods/mock-data.json
- store/test/saga.js
Load all audio files before starting a test to prevent the test from crashing.
Closes #124
> feat: Load audio files before starting a test

- app.json
> chore(release): 0.2.12

- app.json
> chore(release): 0.2.13

- app.json
> chore(release): 0.2.14

- app.json
> chore(release): 0.2.15

- package-lock.json
- package.json
This makes React Devtools work in React Native Debugger.
Closes #164
> chore: React Devtools

- app.json
> chore(release): 0.2.16

- package-lock.json
Generated new lockfile to patch vulnerabilities.
Closes #169
> chore: Patch vulnerabilities

- app.json
> chore(release): 0.2.17

- components/common/atoms/EarLabel.tsx
- components/common/molecules/TestResultItem.tsx
This makes it easier for the user to understand which ear the data in the test result graph belongs to.
Closes #174
> feat: Add labels for test result graph

- app.json
> chore(release): 0.2.18

- app.json
> chore(release): 0.2.19

- app.json
> chore(release): 0.3.0

- app.json
> chore(release): 0.3.2

- package-lock.json
- package.json
- test-results.json
Updated repository name references.
Closes #237
> chore: Rename repository

- .github/workflows/release-please.yml
Release Please automates CHANGELOG generation, the creation of GitHub releases, and version bumps.
Closes #241
> chore: Add Release Please

- package-lock.json
- Generate new `package-lock.json`.
Fixes #273
> fix(deps): Patch vulnerabilities

- components/common/molecules/TestCard.tsx
- screens/BarCodeScannerScreen.tsx
- screens/DefaultScreen.tsx
- screens/PreTestScreen.js
- screens/SoundCheckFinishedScreen.tsx
- screens/SoundCheckScreen.tsx
- screens/TestResultScreen.tsx
> refactor: Adjust screen types

- screens/SoundCheckFinishedScreen.tsx
- screens/SoundCheckScreen.tsx
- Move stylesheets to the bottom of component files.
Closes #307
> refactor: Move stylesheets

- components/common/atoms/EarLabel.tsx
- components/common/atoms/ErrorBanner.tsx
- components/common/atoms/MenuItem.tsx
- components/common/atoms/NavigationItem.tsx
- components/common/atoms/ProgressBar.tsx
- components/common/molecules/Chart.tsx
- components/common/molecules/Indicators.tsx
- components/common/molecules/ProgressAnimationBar.tsx
- components/common/molecules/TestResultChart.tsx
- constants/colors.ts
- navigation/index.tsx
- screens/SoundCheckScreen.tsx
- Export an object with color constants.
- Remove unused color constants.
- Remove duplicate color constants.
Closes #236
> refactor: Clean up color constants

- components/common/molecules/Loading.tsx
- components/common/molecules/TestResultChart.tsx
- components/common/molecules/TestResultsModalContent.tsx
- screens/TestScreen.tsx
- Replace `Spinner` from `mad-expo-core` with `CircularProgress` from `@equinor/mad-components`.
- Add `verticalAlignment` property to `Loading`.
- Add the `verticalAlignment` propery to `Loading` where necessary.
Closes #309
> refactor: Use `CircularProgress` from `@equinor/mad-components`

- package-lock.json
- package.json
- Upgrade mad-expo-core
- Generate new `package-lock.json`
Closes #333
> fix: Upgrade dependencies

- components/common/molecules/TestCard.tsx
- components/common/organisms/README.md
> refactor: Replace redux `connect` with hooks

- contexts/VolumeContext.tsx
- hooks/useInitialSystemVolume.ts
- screens/SoundCheckScreen/SoundCheckScreen.tsx
- screens/SoundCheckScreen/hooks/useSoundCheck.ts
> refactor: Remove duplicate `useInitialSystemVolume`

- package-lock.json
- package.json
> fix: Upgrade @equinor/mad-core from 0.5.4 to 0.5.15

- services/api/api-methods.ts
> refactor: Add missing types

- hooks/useHearingNavigation.ts
- hooks/useHearingTest.ts
- package-lock.json
- package.json
- screens/TestResultScreen.tsx
- screens/TestScreen/TestScreenComponent.tsx
- store/test/actions.ts
- store/test/reducer.ts
- utils/hearing-test/getSubheading.test.ts
- utils/hearing-test/getSubheading.ts
A user was unable to start a second test during the same session since the test state reducer was not reset.
Closes #367
> fix: Unable to start a second test during the same session

- package-lock.json
- package.json
> fix: upgrade mad packages

- constants/env-configs/prod.json
- constants/settings.ts
> fix: use correct env config for prod

- .github/workflows/build-release-ios.yml
> fix: correct file path in build action

- .github/ISSUE_TEMPLATE/release.md
> docs: update issue template for release process

- .github/workflows/build-release-ios.yml
* Adding task: 'Set Xcode version'
* Removing task: 'Xcode Build' as this is not required for sending to TestFlight
> build: reduce build time
